name: tests
run-name: tests run by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  back-end-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install
        working-directory: backend/api
        run: |
          poetry install --with dev
      - name: run tests
        working-directory: backend/api
        run: |
          poetry run python -m pytest tests/
