name: run back-end tests
run-name: ${{ github.actor }}, tests
#on:
#  pull_request:
#    branches:
#      - main
on: [push]
jobs:
  run-tests-with-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install
        working-directory: backend/api
        run: |
          poetry install --with dev
      - name: run tests
        working-directory: backend/api
        run: |
          make test
